name: Prueba ejecución de Script
run-name: Script de Python en Ununtu
on: [push]
jobs:
  ejecuta-script-python:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Inicia Actions"
      - run: python --version
      - run: ls -al
      - run: python app.py
