name: Prueba ejecución de Script de Node
run-name: Script de Node en Ubuntu
on: [push]
jobs:
  ejecuta-script-node:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Inicia Actions"
      - run: node --version
      - name: Check out repository code
        uses: actions/checkout@v6
      - run: ls -al
      - run: node app.js
